graph LR
    root[Projetos: ciencias-da-computacao]
    
    root --> git[.git]
    root --> next[.next]
    root --> mermaid[mermaid]
    root --> node_modules[node_modules]
    root --> public[public]
    root --> src[src]
    root --> config[Arquivos de Configuração]
    
    config --> eslint[.eslintrc.json]
    config --> gitignore[.gitignore]
    config --> nextConfig[next.config.ts]
    config --> tailwind[tailwind.config.ts]
    config --> packageJSON[package.json]
    config --> readme[README.md]

    src --> app[app]
    src --> arquitetura[arquitetura]
    src --> seguranca[seguranca]
    src --> redes[redes]
    src --> introducao[introducao-programacao]
    src --> formacao[formacao-socioemocional]
    src --> sistemas[sistemas-informacao]
